-- データベースの作成
CREATE DATABASE IF NOT EXISTS memo_app CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE memo_app;

-- USERSテーブルの作成
CREATE TABLE IF NOT EXISTS USERS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- MEMOSテーブルの作成
CREATE TABLE IF NOT EXISTS MEMOS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    content TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE
);

-- TAGSテーブルの作成
CREATE TABLE IF NOT EXISTS TAGS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

-- MEMO_TAGSテーブルの作成
CREATE TABLE IF NOT EXISTS MEMO_TAGS (
    memo_id INT NOT NULL,
    tag_id INT NOT NULL,
    PRIMARY KEY (memo_id, tag_id),  -- note_idをmemo_idに変更
    FOREIGN KEY (memo_id) REFERENCES MEMOS(id) ON DELETE CASCADE,  -- note_idをmemo_idに変更
    FOREIGN KEY (tag_id) REFERENCES TAGS(id) ON DELETE CASCADE
);
