-- データベースの作成
CREATE DATABASE IF NOT EXISTS memo_app CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE memo_app;

-- USERSテーブルの作成
CREATE TABLE IF NOT EXISTS USERS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- NOTESテーブルの作成
CREATE TABLE IF NOT EXISTS NOTES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    content TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE
);

-- TAGSテーブルの作成
CREATE TABLE IF NOT EXISTS TAGS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

-- NOTE_TAGSテーブルの作成
CREATE TABLE IF NOT EXISTS NOTE_TAGS (
    note_id INT NOT NULL,
    tag_id INT NOT NULL,
    PRIMARY KEY (note_id, tag_id),
    FOREIGN KEY (note_id) REFERENCES NOTES(id) ON DELETE CASCADE,
    FOREIGN KEY (tag_id) REFERENCES TAGS(id) ON DELETE CASCADE
);


-- NOTESテーブルをMEMOSテーブルに変更
ALTER TABLE NOTES RENAME TO MEMOS;

-- NOTE_TAGSテーブルをMEMO_TAGSテーブルに変更
ALTER TABLE NOTE_TAGS RENAME TO MEMO_TAGS;
